---

packages:
  - python-pip
  - unzip
  - zip
  - screen
  - ntp
  - telnet
  - mlocate
  - figlet
  - nmap
  - lynx
  - python-magic
  - bc
  - git

# Update only security packages via cron (daily,weekly,monthly,yearly)
security_update_schedule: weekly

dirs:
  - "/{{ role_local_facts }}"
  - "/etc/ansible/facts.d"
  - "/{{ cumulus_etc }}/instance_conf.d"