---

- name: Update system packages
  command: yum -y update
  tags:
  - system
  - build
  - packages
  - base

- name: Install packages
  yum: name={{ item }} state=latest enablerepo=epel
  with_items: packages
  tags:
  - system
  - build
  - packages
  - base

- name: Create directories
  file: path={{ item }} state=directory owner=root group=root mode=0755
  with_items: dirs
  tags:
  - system
  - build
  - base

- name: Security Updates
  cron: name="Yum Security Update" special_time='{{ security_update_schedule }}' job="/usr/bin/yum update -y --quiet --security" user="root" cron_file=02yum_security_update
  tags:
  - config
  - build
  - security-config
  - base-config

- name: Local Ansible facts
  template: src={{ role_local_facts }}/base.fact dest=/{{ role_local_facts }}/base.fact owner=root group=root mode=0644
  tags:
  - config
  - build
  - base-config
  - facts

- name: Init.d Script instance_conf
  template: src=etc/init.d/instance_conf dest=/etc/init.d/instance_conf owner=root group=root mode=0755
  tags:
  - system
  - build
  - base
  - instance_conf

- name: instance_conf.d
  template: src={{ cumulus_etc }}/instance_conf.d/00_set_user_data dest=/{{ cumulus_etc }}/instance_conf.d/00_set_user_data owner=root group=root mode=0644
  tags:
  - config
  - build
  - base
  - instance_conf

- name: instance_conf binary
  template: src=usr/bin/instance_conf dest=/usr/bin/instance_conf owner=root group=root mode=0755
  tags:
  - system
  - build
  - base
  - instance_conf

- name: Link Ansible to usr/bin
  file: src=/usr/local/bin/ansible dest=/usr/bin/ansible state=link owner=root group=root
  tags:
  - config
  - build
  - base


