---

- name: Install packages
  yum: name={{ item }} state=latest
  with_items: packages
  tags:
    - system
    - build
    - packages
    - fpm

- name: Update gem
  command: gem update --system
  tags:
    - build
